apiVersion: v2
name: shared-data-provisioner
description: A Helm chart for Kubernetes installing shared-data provisioner (component specified by a label)

type: application
version: 0.2.0
appVersion: "0.1.3-label"
keywords:
  - shared data
  - provisioner
  - single node cluster
  - local disk
home: https://github.com/milan-simanek/shared-data-provisioner
maintainers:
  - name: Milan Šimánek
    email: milan.simanek@seznam.cz
