# namespace where the provisioner pod is running
namespace: shared-data-provisioner

# host-directory where all shared components are located
baseDir: /var/shared-data

# location of OCI image of the provisioner
image: docker.io/milansimanek/shared-data-provisioner:v1.0.0
