apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-data-provisioner
  namespace: shared-data-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      appprov: shared-data-provisioner
  template:
    metadata:
      labels:
        appprov: shared-data-provisioner
    spec:
      serviceAccountName: shared-data-provisioner
      containers:
        - name: provisioner
          image: "milansimanek/shared-data-provisioner:v0.1.2"
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_BASE_DIR
              value: "/var/shared-data"
            - name: HOSTPATH_PROVISIONER_NAME
              value: "shared-data"
          volumeMounts:
            - name: pv-volume
              mountPath: /var/shared-data
      volumes:
        - name: pv-volume
          hostPath:
            path: /var/shared-data
