apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shared-data-provisioner-leader-locking
  namespace: shared-data-provisioner
  labels:
    app.kubernetes.io/name: shared-data-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: shared-data-provisioner-leader-locking
subjects:
  - kind: ServiceAccount
    name: shared-data-provisioner
    namespace: shared-data-provisioner
