apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-data-provisioner
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      appprov: shared-data-provisioner
  template:
    metadata:
      labels:
        appprov: shared-data-provisioner
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: provisioner
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_BASE_DIR
              value: "{{ .Values.baseDir }}"
            - name: HOSTPATH_PROVISIONER_NAME
              value: "shared-data"
          volumeMounts:
            - name: pv-volume
              mountPath: {{ .Values.baseDir }}
      volumes:
        - name: pv-volume
          hostPath:
            path: {{ .Values.baseDir }}
