apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shared-data-provisioner-leader-locking
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["list", "watch", "create"]
