apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: {{ .Values.namespace }}
  labels:
    component: test-data
spec:
  accessModes:
  - ReadOnlyMany
  storageClassName: shared-data
  resources:
    requests:
      storage: 1M
