apiVersion: v2
name: shared-data-test
description: A Helm chart for shared-data provisioner tester

type: application
version: 1.0.0
keywords:
  - shared data
  - provisioner
  - single node cluster
home: https://github.com/milan-simanek/shared-data-provisioner
maintainers:
  - name: Milan Šimánek
    email: milan.simanek@seznam.cz
