apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      component: test-data
  accessModes:
  - ReadOnlyMany
  storageClassName: shared-data
  resources:
    requests:
      storage: 1M
