name: Build and Publish Image

on:
  push:
    branches:
      - main
    paths:
      - 'image/**'


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if the image already exists
        id: check
        run: |
          TAG=$(cat image/tag)
          if docker manifest inspect milansimanek/avrbuid:$TAG > /dev/null 2>&1
          then
            echo "image[$TAG] already exists, nothing to do."
            echo "build=false" >> $GITHUB_OUTPUT
          else
            echo "Image[$TAG] is not present in Docker HUB -> building..."
            echo "build=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Login to Docker Hub
        if: steps.check.outputs.build == 'true'
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
          

      - name: Run make to build and push the image
        if: steps.check.outputs.build == 'true'
        run: make -C image push
 